[package]
name = "runtime-main"
version = "0.1.0"
edition = "2024"

[dependencies]
frida = { version = "0.16.7", features = ["auto-download"] }
#frida-gum = { version = "0.15.1", features = ["auto-download"] }
#frida-build = "0.15.1"
